### PR TITLE
This module also relies on `matchMedia`

### PR DESCRIPTION
**Pull request by matthew-andrews**
note this is dependent on https://github.com/Modernizr/Modernizr/issues/1518

### CODE REVIEW

**Comment by AlbertoElias** [comment]
Well, what we really need is the polyfill service to add a modernizr alias. So it will also be dependent on that

**Comment by matthew-andrews** [comment]
would this be the origami team's responsibility for coordinating?  a component shouldn't use a feature that it can't polyfill imho

**Comment by triblondon** [comment]
Yes, we should.  Alberto can you take it?

**Comment by AlbertoElias** [comment]
Will do

**Comment by AlbertoElias** [comment]
Opened pr in [Modernizr](https://github.com/Modernizr/Modernizr/pull/1520). Will do the same thing to polyfill service once this is merged

**Comment by AlbertoElias** [comment]
Opened pr in [Polyfill Service](https://github.com/Financial-Times/polyfill-service/pull/304)

**Comment by AlbertoElias** [comment]
It was merged into polyfill service

**Pull request merged**
